import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
});

export default [
  // Global ignores: framework-generated files are not reviewable source.
  // next-env.d.ts is regenerated by Next.js itself (and says "do not edit");
  // .next/ is build output. Excluding them scopes the lint to real source.
  { ignores: ["next-env.d.ts", ".next/**"] },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];
