/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/risk-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Risk Session
         * @description Create a new risk session or return existing one on idempotent replay.
         */
        post: operations["create_risk_session_v1_risk_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/risk-sessions/{risk_session_id}/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Record Telemetry
         * @description Record telemetry and transition session to READY.
         */
        patch: operations["record_telemetry_v1_risk_sessions__risk_session_id__telemetry_patch"];
        trace?: never;
    };
    "/v1/risk-sessions/{risk_session_id}/precheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Precheck
         * @description Request a pre-registration risk assessment.
         */
        post: operations["request_precheck_v1_risk_sessions__risk_session_id__precheck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/razorpay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Razorpay Webhook
         * @description Verify, normalise and ingest one Razorpay webhook delivery.
         */
        post: operations["razorpay_webhook_v1_webhooks_razorpay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assessments
         * @description Return the newest redacted assessment projections, newest first.
         */
        get: operations["list_assessments_v1_dashboard_assessments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit Events
         * @description Return one aggregate's audit chain, newest first (A1 payloads as-is).
         */
        get: operations["list_audit_events_v1_dashboard_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/audit-events/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Audit Events
         * @description Verify one aggregate's full audit chain (missing aggregates verify valid/zero).
         */
        get: operations["verify_audit_events_v1_dashboard_audit_events_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Demo Scenarios
         * @description List exactly the seven demo scenarios.
         */
        get: operations["list_demo_scenarios_v1_demo_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/scenarios/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Demo Scenario
         * @description Execute one scenario synchronously and return its per-check verdict.
         */
        post: operations["run_demo_scenario_v1_demo_scenarios__name__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Render the current counters in Prometheus text format.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe — always returns OK if the process is running.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness probe — configuration-only in A0.
         *
         *     A1/A4 may later add actual Postgres/Redis checks without changing
         *     the response shape.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionStatus
         * @description Lifecycle status of an action request or attempt.
         * @enum {string}
         */
        ActionStatus: "QUEUED" | "IN_PROGRESS" | "SUCCEEDED" | "RETRYING" | "FAILED" | "NOT_REQUIRED";
        /**
         * AuditActorType
         * @description Who or what created an audit event.
         * @enum {string}
         */
        AuditActorType: "SYSTEM" | "WEBHOOK" | "WORKER" | "OPERATOR" | "DEMO";
        /** AuditVerificationResponse */
        AuditVerificationResponse: {
            /** Valid */
            valid: boolean;
            /** Checked Events */
            checked_events: number;
            /** First Invalid Sequence */
            first_invalid_sequence?: number | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * DashboardAssessmentItem
         * @example {
         *       "action_status": "SUCCEEDED",
         *       "assessed_at": "2026-01-15T10:02:03Z",
         *       "assessment_id": "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f80",
         *       "decision": "BLOCK",
         *       "evaluation_latency_ms": 12,
         *       "is_demo_event": false,
         *       "reasons": [
         *         {
         *           "points": 25,
         *           "reason_code": "DEVICE_VELOCITY_BURST",
         *           "reason_text": "Device made 7 registrations in 5 minutes.",
         *           "rule_id": "velocity_device_burst"
         *         }
         *       ],
         *       "score": 80,
         *       "stage": "POST_CONFIRMATION",
         *       "token_id": "token_demo123",
         *       "vpa_handle": "upi"
         *     }
         */
        DashboardAssessmentItem: {
            /**
             * Assessment Id
             * Format: uuid
             */
            assessment_id: string;
            decision: components["schemas"]["Decision"];
            /** Score */
            score: number;
            stage: components["schemas"]["DecisionStage"];
            /**
             * Assessed At
             * Format: date-time
             */
            assessed_at: string;
            /** Evaluation Latency Ms */
            evaluation_latency_ms: number;
            /** Token Id */
            token_id?: string | null;
            /** Vpa Handle */
            vpa_handle?: string | null;
            /**
             * Is Demo Event
             * @default false
             */
            is_demo_event: boolean;
            action_status?: components["schemas"]["ActionStatus"] | null;
            /** Reasons */
            reasons?: components["schemas"]["DashboardReasonItem"][];
        };
        /** DashboardAssessmentsResponse */
        DashboardAssessmentsResponse: {
            /** Items */
            items: components["schemas"]["DashboardAssessmentItem"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** DashboardAuditItem */
        DashboardAuditItem: {
            /**
             * Audit Event Id
             * Format: uuid
             */
            audit_event_id: string;
            /** Sequence Number */
            sequence_number: number;
            /** Event Type */
            event_type: string;
            actor_type: components["schemas"]["AuditActorType"];
            /** Actor Id */
            actor_id?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Redacted Payload */
            redacted_payload: {
                [key: string]: unknown;
            };
        };
        /** DashboardReasonItem */
        DashboardReasonItem: {
            /** Rule Id */
            rule_id: string;
            /** Reason Code */
            reason_code?: string | null;
            /** Reason Text */
            reason_text?: string | null;
            /**
             * Points
             * @default 0
             */
            points: number;
        };
        /**
         * Decision
         * @description Outcome of a risk evaluation.
         * @enum {string}
         */
        Decision: "ALLOW" | "CHALLENGE" | "BLOCK";
        /**
         * DecisionStage
         * @description The phase of the mandate lifecycle at which the decision was made.
         * @enum {string}
         */
        DecisionStage: "PRECHECK" | "POST_CONFIRMATION" | "REJECTION_AUDIT";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MandateIntent
         * @description The mandate parameters the customer intends to register.
         * @example {
         *       "expire_at": "2027-01-15T10:00:00Z",
         *       "frequency": "monthly",
         *       "max_amount_paise": 500000
         *     }
         */
        MandateIntent: {
            /**
             * Max Amount Paise
             * @default null
             */
            max_amount_paise: number | null;
            /**
             * Frequency
             * @default null
             */
            frequency: string | null;
            /**
             * Expire At
             * @default null
             */
            expire_at: string | null;
        };
        /**
         * RiskAssessment
         * @description Immutable risk assessment produced by the rule engine.
         * @example {
         *       "assessed_at": "2026-01-15T10:02:03Z",
         *       "assessment_id": "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f80",
         *       "decision": "BLOCK",
         *       "engine_version": "rules-v1",
         *       "evaluation_latency_ms": 12,
         *       "feature_snapshot_id": "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
         *       "mandate_event_id": "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
         *       "risk_session_id": null,
         *       "rule_evaluations": [
         *         {
         *           "points": 25,
         *           "reason_code": "IP_VELOCITY_5M",
         *           "reason_text": "IP address seen in 15 registrations in 5 minutes.",
         *           "rule_id": "ip_velocity_5m_high",
         *           "triggered": true
         *         }
         *       ],
         *       "schema_version": "1.0",
         *       "score": 85,
         *       "stage": "POST_CONFIRMATION"
         *     }
         */
        RiskAssessment: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Assessment Id
             * Format: uuid
             */
            assessment_id?: string;
            /**
             * Risk Session Id
             * @default null
             */
            risk_session_id: string | null;
            /**
             * Mandate Event Id
             * @default null
             */
            mandate_event_id: string | null;
            /**
             * Feature Snapshot Id
             * Format: uuid
             */
            feature_snapshot_id: string;
            stage: components["schemas"]["DecisionStage"];
            /** Score */
            score: number;
            decision: components["schemas"]["Decision"];
            /**
             * Engine Version
             * @default rules-v1
             */
            engine_version: string;
            /** Rule Evaluations */
            rule_evaluations: components["schemas"]["RuleEvaluation"][];
            /** Evaluation Latency Ms */
            evaluation_latency_ms: number;
            /**
             * Assessed At
             * Format: date-time
             */
            assessed_at: string;
        };
        /**
         * RiskSession
         * @description Pseudonymised risk session — the output contract.
         *
         *     Never contains raw customer_reference, raw IP, raw device fingerprint or
         *     raw user-agent. Only HMAC hashes of those values are stored.
         * @example {
         *       "checkout_order_ref": "order_demo_001",
         *       "created_at": "2026-01-15T10:00:00Z",
         *       "customer_reference_hash": "hmac-sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
         *       "device_fingerprint_hash": null,
         *       "flow_completed_at": "2026-01-15T10:05:00Z",
         *       "flow_started_at": "2026-01-15T10:00:00Z",
         *       "ip_hash": null,
         *       "mandate_intent": {
         *         "expire_at": "2027-01-15T10:00:00Z",
         *         "frequency": "monthly",
         *         "max_amount_paise": 500000
         *       },
         *       "merchant_namespace": "demo-merchant-01",
         *       "risk_session_id": "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
         *       "schema_version": "1.0",
         *       "status": "CREATED",
         *       "updated_at": "2026-01-15T10:00:00Z",
         *       "user_agent_hash": null
         *     }
         */
        RiskSession: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Risk Session Id
             * Format: uuid
             */
            risk_session_id?: string;
            /** Merchant Namespace */
            merchant_namespace: string;
            /**
             * Checkout Order Ref
             * @default null
             */
            checkout_order_ref: string | null;
            /**
             * Customer Reference Hash
             * @default null
             */
            customer_reference_hash: string | null;
            /**
             * Ip Hash
             * @default null
             */
            ip_hash: string | null;
            /**
             * Device Fingerprint Hash
             * @default null
             */
            device_fingerprint_hash: string | null;
            /**
             * User Agent Hash
             * @default null
             */
            user_agent_hash: string | null;
            /**
             * Flow Started At
             * @default null
             */
            flow_started_at: string | null;
            /**
             * Flow Completed At
             * @default null
             */
            flow_completed_at: string | null;
            mandate_intent: components["schemas"]["MandateIntent"];
            status: components["schemas"]["RiskSessionStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RiskSessionCreateRequest
         * @description Request body to create a new checkout risk session.
         * @example {
         *       "checkout_order_ref": "order_demo_001",
         *       "customer_reference": "cust_demo_ref_sensitive",
         *       "device_fingerprint": "fp_ab12cd34ef56gh78",
         *       "flow_started_at": "2026-01-15T10:00:00Z",
         *       "mandate_intent": {
         *         "expire_at": "2027-01-15T10:00:00Z",
         *         "frequency": "monthly",
         *         "max_amount_paise": 500000
         *       },
         *       "merchant_namespace": "demo-merchant-01"
         *     }
         */
        RiskSessionCreateRequest: {
            /** Merchant Namespace */
            merchant_namespace: string;
            /**
             * Checkout Order Ref
             * @default null
             */
            checkout_order_ref: string | null;
            /**
             * Customer Reference
             * @default null
             */
            customer_reference: string | null;
            /**
             * Device Fingerprint
             * @default null
             */
            device_fingerprint: string | null;
            /**
             * Flow Started At
             * @default null
             */
            flow_started_at: string | null;
            mandate_intent: components["schemas"]["MandateIntent"];
        };
        /**
         * RiskSessionStatus
         * @description Lifecycle status of a checkout risk session.
         * @enum {string}
         */
        RiskSessionStatus: "CREATED" | "READY" | "CONSUMED" | "EXPIRED";
        /**
         * RiskSessionTelemetryUpdateRequest
         * @description Partial update for telemetry captured during the checkout flow.
         * @example {
         *       "client_ip": "192.168.1.100",
         *       "client_user_agent": "Mozilla/5.0 (Linux; Android 14)",
         *       "device_fingerprint": "fp_ab12cd34ef56gh78",
         *       "flow_completed_at": "2026-01-15T10:05:00Z",
         *       "is_vpn_claimed": false
         *     }
         */
        RiskSessionTelemetryUpdateRequest: {
            /**
             * Device Fingerprint
             * @default null
             */
            device_fingerprint: string | null;
            /**
             * Flow Completed At
             * @default null
             */
            flow_completed_at: string | null;
            /**
             * Client User Agent
             * @default null
             */
            client_user_agent: string | null;
            /**
             * Client Ip
             * @default null
             */
            client_ip: string | null;
            /**
             * Is Vpn Claimed
             * @default null
             */
            is_vpn_claimed: boolean | null;
        };
        /**
         * RuleEvaluation
         * @description Result of evaluating a single rule against a feature snapshot.
         * @example {
         *       "points": 25,
         *       "reason_code": "IP_VELOCITY_5M",
         *       "reason_text": "IP address seen in 15 registrations in the last 5 minutes.",
         *       "rule_id": "ip_velocity_5m_high",
         *       "triggered": true
         *     }
         */
        RuleEvaluation: {
            /** Rule Id */
            rule_id: string;
            /** Triggered */
            triggered: boolean;
            /** Points */
            points: number;
            /**
             * Reason Code
             * @default null
             */
            reason_code: string | null;
            /**
             * Reason Text
             * @default null
             */
            reason_text: string | null;
        };
        /** ScenarioCheckItem */
        ScenarioCheckItem: {
            /** Check */
            check: string;
            /** Passed */
            passed: boolean;
            /** Detail */
            detail: string;
        };
        /** ScenarioListResponse */
        ScenarioListResponse: {
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioSummaryItem"][];
        };
        /** ScenarioRunResponse */
        ScenarioRunResponse: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Checks */
            checks?: components["schemas"]["ScenarioCheckItem"][];
        };
        /** ScenarioSummaryItem */
        ScenarioSummaryItem: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Expected Outcome */
            expected_outcome: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ActionAttempt
         * @description A single attempt to execute a queued action.
         *
         *     ``safe_error_message`` must never be a raw upstream body.
         * @example {
         *       "action_attempt_id": "f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f809102",
         *       "action_request_id": "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8091",
         *       "attempt_number": 1,
         *       "attempted_at": "2026-01-15T10:02:05Z",
         *       "completed_at": null,
         *       "provider_status_code": 503,
         *       "safe_error_code": "PROVIDER_UNAVAILABLE",
         *       "safe_error_message": "Token revoke service temporarily unavailable.",
         *       "schema_version": "1.0",
         *       "status": "RETRYING"
         *     }
         */
        ActionAttempt: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Action Attempt Id
             * Format: uuid
             */
            action_attempt_id?: string;
            /**
             * Action Request Id
             * Format: uuid
             */
            action_request_id: string;
            /** Attempt Number */
            attempt_number: number;
            status: components["schemas"]["ActionStatus"];
            /**
             * Provider Status Code
             * @default null
             */
            provider_status_code: number | null;
            /**
             * Safe Error Code
             * @default null
             */
            safe_error_code: string | null;
            /**
             * Safe Error Message
             * @default null
             */
            safe_error_message: string | null;
            /**
             * Attempted At
             * Format: date-time
             */
            attempted_at: string;
            /**
             * Completed At
             * @default null
             */
            completed_at: string | null;
        };
        /**
         * ActionRequest
         * @description A queued request for a downstream action (e.g. token revocation).
         * @example {
         *       "action_request_id": "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8091",
         *       "action_type": "TOKEN_REVOKE",
         *       "assessment_id": "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f80",
         *       "idempotency_key": "revoke-token_demo123-d4e5f6a7",
         *       "mandate_event_id": "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
         *       "requested_at": "2026-01-15T10:02:04Z",
         *       "schema_version": "1.0",
         *       "status": "QUEUED",
         *       "token_id": "token_demo123"
         *     }
         */
        ActionRequest: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Action Request Id
             * Format: uuid
             */
            action_request_id?: string;
            /**
             * Assessment Id
             * Format: uuid
             */
            assessment_id: string;
            /**
             * Mandate Event Id
             * Format: uuid
             */
            mandate_event_id: string;
            action_type: components["schemas"]["ActionType"];
            /** Token Id */
            token_id: string;
            /** Idempotency Key */
            idempotency_key: string;
            status: components["schemas"]["ActionStatus"];
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
        };
        /**
         * ActionType
         * @description Types of downstream actions the system can request.
         * @enum {string}
         */
        ActionType: "TOKEN_REVOKE";
        /**
         * AuditEvent
         * @description Immutable, hash-chained audit event.
         *
         *     The first event in an aggregate has ``previous_event_hash=None``;
         *     subsequent events require it. A1 determines hash generation.
         * @example {
         *       "actor_id": null,
         *       "actor_type": "SYSTEM",
         *       "aggregate_id": "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f80",
         *       "aggregate_type": "risk_assessment",
         *       "audit_event_id": "a7b8c9d0-e1f2-4a3b-4c5d-6e7f80910213",
         *       "event_hash": "sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
         *       "event_type": "risk_assessment.created",
         *       "occurred_at": "2026-01-15T10:02:03Z",
         *       "previous_event_hash": null,
         *       "redacted_payload": {
         *         "decision": "BLOCK",
         *         "score": 85
         *       },
         *       "schema_version": "1.0",
         *       "sequence_number": 1
         *     }
         */
        AuditEvent: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Audit Event Id
             * Format: uuid
             */
            audit_event_id?: string;
            /**
             * Aggregate Type
             * @enum {string}
             */
            aggregate_type: "risk_session" | "mandate_event" | "risk_assessment" | "action_request";
            /**
             * Aggregate Id
             * Format: uuid
             */
            aggregate_id: string;
            /** Sequence Number */
            sequence_number: number;
            /** Event Type */
            event_type: string;
            actor_type: components["schemas"]["AuditActorType"];
            /**
             * Actor Id
             * @default null
             */
            actor_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Redacted Payload */
            redacted_payload: {
                [key: string]: unknown;
            };
            /**
             * Previous Event Hash
             * @default null
             */
            previous_event_hash: string | null;
            /**
             * Event Hash
             * @description SHA-256 hash prefixed with 'sha256:'.
             */
            event_hash: string;
        };
        /**
         * Availability
         * @description Whether a feature source was available at evaluation time.
         * @enum {string}
         */
        Availability: "AVAILABLE" | "MISSING" | "NOT_APPLICABLE" | "DEMO_SIMULATED";
        /**
         * ContractModel
         * @description Base model for all canonical API and event contracts.
         *
         *     Enforces:
         *     - ``extra="forbid"`` to reject undeclared fields.
         *     - ``populate_by_name=True`` for flexible construction.
         *     - ``str_strip_whitespace=True`` to normalise string inputs.
         *     - JSON-mode serialisation of UUIDs and datetimes.
         */
        ContractModel: Record<string, never>;
        /**
         * FeatureSnapshot
         * @description Immutable point-in-time feature vector for a mandate event or session.
         *
         *     All feature calculations must be explicit, typed and named. This model
         *     carries the shape without computation logic.
         * @example {
         *       "calculated_at": "2026-01-15T10:02:02Z",
         *       "customer_velocity_1h": 1,
         *       "device_velocity_1h": 4,
         *       "device_velocity_5m": 2,
         *       "expiry_days_from_registration": 365,
         *       "feature_snapshot_id": "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
         *       "feature_version": "rules-v1",
         *       "flow_duration_seconds": 45,
         *       "ip_velocity_1h": 5,
         *       "ip_velocity_5m": 3,
         *       "is_demo_simulation": false,
         *       "is_new_device_for_customer": false,
         *       "mandate_event_id": "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
         *       "mandate_frequency": "monthly",
         *       "max_amount_paise": 500000,
         *       "network_reputation_score": 20,
         *       "network_vpn_or_proxy": false,
         *       "npci_risk_flag": false,
         *       "payer_bank_or_compliance_flag": false,
         *       "risk_session_id": null,
         *       "schema_version": "1.0",
         *       "shared_demo_merchant_count_1h": null,
         *       "sources": {
         *         "ip_velocity_5m": {
         *           "availability": "AVAILABLE",
         *           "captured_at": "2026-01-15T10:02:01Z",
         *           "source": "redis-sliding-window"
         *         }
         *       },
         *       "user_agent_bot_suspected": false,
         *       "vpa_velocity_1h": 1
         *     }
         */
        FeatureSnapshot: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Feature Snapshot Id
             * Format: uuid
             */
            feature_snapshot_id?: string;
            /**
             * Mandate Event Id
             * @default null
             */
            mandate_event_id: string | null;
            /**
             * Risk Session Id
             * @default null
             */
            risk_session_id: string | null;
            /**
             * Feature Version
             * @default rules-v1
             */
            feature_version: string;
            /**
             * Calculated At
             * Format: date-time
             */
            calculated_at: string;
            /**
             * Ip Velocity 5M
             * @default null
             */
            ip_velocity_5m: number | null;
            /**
             * Ip Velocity 1H
             * @default null
             */
            ip_velocity_1h: number | null;
            /**
             * Device Velocity 5M
             * @default null
             */
            device_velocity_5m: number | null;
            /**
             * Device Velocity 1H
             * @default null
             */
            device_velocity_1h: number | null;
            /**
             * Customer Velocity 1H
             * @default null
             */
            customer_velocity_1h: number | null;
            /**
             * Vpa Velocity 1H
             * @default null
             */
            vpa_velocity_1h: number | null;
            /**
             * Shared Demo Merchant Count 1H
             * @default null
             */
            shared_demo_merchant_count_1h: number | null;
            /**
             * Is New Device For Customer
             * @default null
             */
            is_new_device_for_customer: boolean | null;
            /**
             * Flow Duration Seconds
             * @default null
             */
            flow_duration_seconds: number | null;
            /**
             * User Agent Bot Suspected
             * @default null
             */
            user_agent_bot_suspected: boolean | null;
            /**
             * Network Vpn Or Proxy
             * @default null
             */
            network_vpn_or_proxy: boolean | null;
            /**
             * Network Reputation Score
             * @default null
             */
            network_reputation_score: number | null;
            /**
             * Npci Risk Flag
             * @default null
             */
            npci_risk_flag: boolean | null;
            /**
             * Payer Bank Or Compliance Flag
             * @default null
             */
            payer_bank_or_compliance_flag: boolean | null;
            /**
             * Max Amount Paise
             * @default null
             */
            max_amount_paise: number | null;
            /**
             * Mandate Frequency
             * @default null
             */
            mandate_frequency: string | null;
            /**
             * Expiry Days From Registration
             * @default null
             */
            expiry_days_from_registration: number | null;
            /** Sources */
            sources: {
                [key: string]: components["schemas"]["FeatureSource"];
            };
            /**
             * Is Demo Simulation
             * @default false
             */
            is_demo_simulation: boolean;
        };
        /**
         * FeatureSource
         * @description Describes the provenance and availability of a single feature value.
         *
         *     When availability is ``AVAILABLE`` or ``DEMO_SIMULATED``, ``captured_at``
         *     is required. Otherwise it must be ``None``.
         * @example {
         *       "availability": "AVAILABLE",
         *       "captured_at": "2026-01-15T10:01:00Z",
         *       "source": "redis-sliding-window"
         *     }
         */
        FeatureSource: {
            availability: components["schemas"]["Availability"];
            /** Source */
            source: string;
            /**
             * Captured At
             * @default null
             */
            captured_at: string | null;
        };
        /**
         * MandateEventType
         * @description Razorpay webhook event types for recurring mandates.
         * @enum {string}
         */
        MandateEventType: "token.confirmed" | "token.rejected" | "token.cancelled";
        /**
         * MandateWebhookEvent
         * @description Normalised mandate webhook event — no raw payload or raw VPA.
         * @example {
         *       "event_type": "token.confirmed",
         *       "failure_reason": null,
         *       "is_demo_event": true,
         *       "mandate_event_id": "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
         *       "provider": "razorpay",
         *       "provider_created_at": "2026-01-15T10:02:00Z",
         *       "provider_event_id": "evt_demo_confirmed_001",
         *       "raw_payload_sha256": "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
         *       "received_at": "2026-01-15T10:02:01Z",
         *       "recurring_status": "confirmed",
         *       "risk_session_id": "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
         *       "schema_version": "1.0",
         *       "token_id": "token_demo123",
         *       "vpa_handle": "upi",
         *       "vpa_hash": "hmac-sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
         *     }
         */
        MandateWebhookEvent: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Mandate Event Id
             * Format: uuid
             */
            mandate_event_id?: string;
            /**
             * Provider
             * @default razorpay
             * @constant
             */
            provider: "razorpay";
            /** Provider Event Id */
            provider_event_id: string;
            event_type: components["schemas"]["MandateEventType"];
            /** Token Id */
            token_id: string;
            /**
             * Risk Session Id
             * @default null
             */
            risk_session_id: string | null;
            /**
             * Vpa Hash
             * @default null
             */
            vpa_hash: string | null;
            /**
             * Vpa Handle
             * @default null
             */
            vpa_handle: string | null;
            /**
             * Recurring Status
             * @default null
             */
            recurring_status: string | null;
            /**
             * Failure Reason
             * @default null
             */
            failure_reason: string | null;
            /**
             * Provider Created At
             * @default null
             */
            provider_created_at: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Raw Payload Sha256 */
            raw_payload_sha256: string;
            /**
             * Is Demo Event
             * @default false
             */
            is_demo_event: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_risk_session_v1_risk_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                "x-forwarded-for"?: string | null;
                "user-agent"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskSessionCreateRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay */
            200: {
                headers: {
                    "X-Idempotent-Replay"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_telemetry_v1_risk_sessions__risk_session_id__telemetry_patch: {
        parameters: {
            query?: never;
            header?: {
                "x-forwarded-for"?: string | null;
                "user-agent"?: string | null;
            };
            path: {
                risk_session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskSessionTelemetryUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskSession"];
                };
            };
            /** @description Risk session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Risk session is already consumed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_precheck_v1_risk_sessions__risk_session_id__precheck_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                risk_session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskAssessment"];
                };
            };
            /** @description Risk session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Risk session telemetry is not ready / inconsistent state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Precheck evaluator is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    razorpay_webhook_v1_webhooks_razorpay_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_assessments_v1_dashboard_assessments_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                decision?: components["schemas"]["Decision"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardAssessmentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_events_v1_dashboard_audit_events_get: {
        parameters: {
            query: {
                aggregate_type: "risk_session" | "mandate_event" | "risk_assessment" | "action_request";
                aggregate_id: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardAuditItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_audit_events_v1_dashboard_audit_events_verify_get: {
        parameters: {
            query: {
                aggregate_type: "risk_session" | "mandate_event" | "risk_assessment" | "action_request";
                aggregate_id: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_demo_scenarios_v1_demo_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioListResponse"];
                };
            };
        };
    };
    run_demo_scenario_v1_demo_scenarios__name__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
